"""onboarding tables

Revision ID: 0002_onboarding
Revises: 0001_foundation
Create Date: 2026-07-06 12:19:05.029604+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_onboarding'
down_revision: Union[str, None] = '0001_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('society_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('numbering_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'name', name='uq_buildings_society_name')
    )
    op.create_index('ix_buildings_society', 'buildings', ['society_id'], unique=False)
    op.create_table('onboarding_progress',
    sa.Column('society_id', sa.BigInteger(), nullable=False),
    sa.Column('type_selected', sa.String(length=32), nullable=True),
    sa.Column('current_step', sa.String(length=64), server_default='type_selection', nullable=False),
    sa.Column('current_building_index', sa.Integer(), nullable=True),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('numbering_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', name='uq_onboarding_progress_society')
    )
    op.create_table('rows',
    sa.Column('society_id', sa.BigInteger(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('houses_count', sa.Integer(), nullable=False),
    sa.Column('numbering_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('both_sides', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'display_order', name='uq_rows_society_order')
    )
    op.create_index('ix_rows_society', 'rows', ['society_id'], unique=False)
    op.create_table('floors',
    sa.Column('society_id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_ground', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('houses_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'level', name='uq_floors_building_level')
    )
    op.create_index('ix_floors_building', 'floors', ['building_id'], unique=False)
    op.create_index('uq_floors_building_ground', 'floors', ['building_id'], unique=True, postgresql_where=sa.text('is_ground = true'))
    op.create_table('houses',
    sa.Column('society_id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=True),
    sa.Column('floor_id', sa.BigInteger(), nullable=True),
    sa.Column('row_id', sa.BigInteger(), nullable=True),
    sa.Column('position_in_row', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('numbering_mode', sa.String(length=16), nullable=False),
    sa.Column('number_overridden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='empty', nullable=False),
    sa.Column('first_left_empty_on', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['rows.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_houses_society_status', 'houses', ['society_id', 'status'], unique=False)
    op.create_index('uq_houses_building_number', 'houses', ['society_id', 'building_id', 'number'], unique=True, postgresql_where=sa.text('building_id IS NOT NULL'))
    op.create_index('uq_houses_individual_number', 'houses', ['society_id', 'number'], unique=True, postgresql_where=sa.text('building_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_houses_individual_number', table_name='houses', postgresql_where=sa.text('building_id IS NULL'))
    op.drop_index('uq_houses_building_number', table_name='houses', postgresql_where=sa.text('building_id IS NOT NULL'))
    op.drop_index('ix_houses_society_status', table_name='houses')
    op.drop_table('houses')
    op.drop_index('uq_floors_building_ground', table_name='floors', postgresql_where=sa.text('is_ground = true'))
    op.drop_index('ix_floors_building', table_name='floors')
    op.drop_table('floors')
    op.drop_index('ix_rows_society', table_name='rows')
    op.drop_table('rows')
    op.drop_table('onboarding_progress')
    op.drop_index('ix_buildings_society', table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
